### ISSUE TITLE
Tracking issue for audio streaming

### ISSUE THREAD

**Issue by TimDiekmann** [clp-research/slurk#46]
**Requirements (non-exhaustive)**
- [ ] Send audio to server via
  - [ ] streaming
  - [ ] record and send
- [x] Distribute audio to clients
- [ ] Save audio and link it in log files

**Unresolved questions**

- [x] Which framework makes the most sense for our use-case?
- [x] Which security requirements to we need here?
- [x] Where do we want to safe the audio?
- [ ] What legal constraints must we take into account?
