### ISSUE TITLE
Tracking issue for video streaming

### ISSUE THREAD

**Issue by TimDiekmann** [clp-research/slurk#47]
**Requirements (non-exhaustive)**
- [x] Send video to server via
  - [x] streaming
- [x] Distribute video to clients
- [ ] Save video and link it in log files

**Unresolved questions**

- [x] Which framework makes the most sense for our use-case?
- [ ] Which security requirements to we need here?
- [ ] Where do we want to safe the video?
- [ ] What legal constraints must we take into account?

**Comment by davidschlangen** [comment]
Evaluate http://www.kurento.org
From a quick glance, it looks like it does all we need (setting up audio / video connections via a server, allowing to record stream).
Maybe the easiest would be to integrate this as a plugin / use slurk to start the conversation.
Problem: for some usecases, we may want to allow other actions in slurk, eg mouse actions. So synchronisation needs to be guaranteed.
